import React from 'react';
import { formatCurrency } from '../services/calculationEngine';
import './PitchDeckChart.css';

const PitchDeckChart = ({ metrics, productName }) => {
    return (
        <div id="pitch-deck-export" className="pitch-deck-container">
            <div className="pitch-deck-header">
                <h2>{productName || 'Market Analysis'}</h2>
                <p>TAM / SAM / SOM Analysis</p>
            </div>

            <div className="target-visual">
                {/* TAM - Outer */}
                <div className="circle tam-circle">
                    <div className="circle-label top">TAM: {formatCurrency(metrics.tam)}</div>

                    {/* SAM - Middle */}
                    <div className="circle sam-circle">
                        <div className="circle-label middle">SAM: {formatCurrency(metrics.sam)}</div>

                        {/* SOM - Inner */}
                        <div className="circle som-circle">
                            <div className="circle-label bottom">SOM: {formatCurrency(metrics.som)}</div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="pitch-deck-footer">
                <div className="footer-metric">
                    <strong>TAM</strong>
                    <span>Total Market</span>
                </div>
                <div className="footer-metric">
                    <strong>SAM</strong>
                    <span>Serviceable Market</span>
                </div>
                <div className="footer-metric">
                    <strong>SOM</strong>
                    <span>Obtainable Market</span>
                </div>
                <div className="powered-by">Generated by ZAM</div>
            </div>
        </div>
    );
};

export default PitchDeckChart;
